spring:
  datasource:
    url: jdbc:mysql://140.143.203.127:3306/simonBlog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: lixiaomeng163@163.com
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.devfuns.model
  configuration:
    map-underscore-to-camel-case: true


# jwt 生成token的私钥及token的有效时间
jwt:
  expiration: 1800
  secret: simon_bolg
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
