package com.devfuns.mapper;

import com.devfuns.model.article.Logs;

public interface LogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    int insert(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    int insertSelective(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    Logs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    int updateByPrimaryKeySelective(Logs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logs
     *
     * @mbggenerated Wed Aug 29 20:02:02 CST 2018
     */
    int updateByPrimaryKey(Logs record);
}