package com.devfuns.mapper;

import com.devfuns.model.article.Metas;

public interface MetasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    int insert(Metas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    int insertSelective(Metas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    Metas selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    int updateByPrimaryKeySelective(Metas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_metas
     *
     * @mbggenerated Wed Aug 29 20:16:45 CST 2018
     */
    int updateByPrimaryKey(Metas record);
}