package com.devfuns.mapper;

import com.devfuns.model.article.RelationshipsKey;

public interface RelationshipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbggenerated Wed Aug 29 20:17:35 CST 2018
     */
    int deleteByPrimaryKey(RelationshipsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbggenerated Wed Aug 29 20:17:35 CST 2018
     */
    int insert(RelationshipsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationships
     *
     * @mbggenerated Wed Aug 29 20:17:35 CST 2018
     */
    int insertSelective(RelationshipsKey record);
}