spring:
  datasource:
    url: jdbc:mysql://39.108.1.7:3306/springCloud?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: lixiaomeng163@163.com
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-user
eureka:
  client:
    service-url:
      defaultZone: http://service1:9001/eureka/

---
spring:
  profiles: user1
server:
  port: 9010
  context-path: /spring-user

---

spring:
  profiles: user2
server:
  port: 9011
  context-path: /spring-user
